# Generated by Django 4.1 on 2022-08-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intercorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'intercorrencia',
            },
        ),
    ]
