# Generated by Django 4.1 on 2022-09-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_evento_delete_intercorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.IntegerField()),
                ('telefone', models.IntegerField()),
            ],
        ),
       
    ]
