# Generated by Django 4.1 on 2022-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_cuidador_delete_intercorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.IntegerField()),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('medico', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'paciente'

            },
        ),
       
    ]
